#%%
def multiplydivide(m1: float, m2: float, d1: float) -> float:
    """Multiply 2 numbers and divide by a third.

    This is a simple example function intended for use in documentation
    generated by mkdocstrings.

    Args:
        m1: The first number to be multiplied.
        m2: The second number to be multiplied.
        d1: The number to divide the product of ``m1`` and ``m2`` by.

    Returns:
        The product of ``m1`` and ``m2`` divided by ``d1``.

    Examples:
        >>> multiplydivide(3, 4, 2)
        6.0
        >>> multiplydivide(5, 2, 1)
        10.0
    """
    return m1 * m2 / d1

# %%
